### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.inotify.InotifyManager

### ISSUE THREAD

**Issue by mrmann** [droboports/crashplan#15] opened 2015-10-05 20:55 UTC
i am getting this error when backup starts (4.4.1)

Exception in thread "W13005329_ScanWrkr" java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.inotify.InotifyManager
        at com.code42.jna.inotify.JNAInotifyFileWatcherDriver.<init>(JNAInotifyFileWatcherDriver.java:22)
        at com.code42.backup.path.BackupSetsManager.initFileWatcherDriver(BackupSetsManager.java:417)
        at com.code42.backup.path.BackupSetsManager.startScheduledFileQueue(BackupSetsManager.java:355)
        at com.code42.backup.path.BackupSetsManager.access$1600(BackupSetsManager.java:72)
        at com.code42.backup.path.BackupSetsManager$ScanWorker.delay(BackupSetsManager.java:1148)
        at com.code42.utils.AWorker.run(AWorker.java:157)
        at java.lang.Thread.run(Unknown Source)

**Comment by ricardopadilha** [comment] 2015-10-05 20:58
Is this on a DroboFS or Drobo5N?

**Comment by mrmann** [comment] 2015-10-05 21:04
Drobo5N

**Comment by ricardopadilha** [comment] 2015-10-05 21:10
Is this an upgrade or a fresh install?

**Comment by mrmann** [comment] 2015-10-05 21:10
upgrade

**Comment by ricardopadilha** [comment] 2015-10-05 21:20
Do you have a file called `jna.jar` and `jna-platform.jar`? If so what are their `md5sum`?

For reference:
```
# md5sum crashplan/app/lib/jna*.jar 
533e404eda70bbf8e40de134ffeec95b  crashplan/app/lib/jna-platform.jar
b0e08c9936dc52aa40439c71fcad6297  crashplan/app/lib/jna.jar
```

**Comment by mrmann** [comment] 2015-10-05 21:22
# md5sum app/lib/jna*.jar
f309b9de85e9a0acdb46e398917e5afb  app/lib/jna-3.2.5.jar
533e404eda70bbf8e40de134ffeec95b  app/lib/jna-platform.jar
b0e08c9936dc52aa40439c71fcad6297  app/lib/jna.jar

**Comment by ricardopadilha** [comment] 2015-10-05 21:23
Could you please restart crashplan? I think the update did not restart crashplan correctly.

**Comment by mrmann** [comment] 2015-10-05 21:24
already did that... and restarted the drobo as well...

**Comment by mrmann** [comment] 2015-10-05 21:31
i removed the crashplan folder and did fresh installation and everything is working fine now... 

maybe there is a problem with the upgrade process...

**Comment by ricardopadilha** [comment] 2015-10-05 21:45
I was going to ask about the md5sum of `com.backup42.desktop.jar`. The error you are seeing seems to be caused by crashplan not finding the proper jar in its classpath, which can only be caused if `com.backup42.desktop.jar` is an old version. Here's the md5sum of the new one for reference:
```
# md5sum crashplan/app/lib/com.backup42.desktop.jar 
ba265969752e364cdb6ea2d784ce0373  crashplan/app/lib/com.backup42.desktop.jar
```
Since we can't reproduce this anymore, I'll close this issue. If you manage to reproduce this please reopen it.

**Closed by ricardopadilha** 2015-10-05 21:45 UTC

**Comment by dmzettl** [comment] 2015-10-10 04:56
I experience the same problem. I have the following md5sum hashes:

```
7373357e5aa91af79235b8a243c0e66d  /mnt/DroboFS/Shares/DroboApps/crashplan/app/lib/jna-3.2.5.jar
533e404eda70bbf8e40de134ffeec95b  /mnt/DroboFS/Shares/DroboApps/crashplan/app/lib/jna-platform.jar
b0e08c9936dc52aa40439c71fcad6297  /mnt/DroboFS/Shares/DroboApps/crashplan/app/lib/jna.jar
```
and 

```
ba265969752e364cdb6ea2d784ce0373  /mnt/DroboFS/Shares/DroboApps/crashplan/app/lib/com.backup42.desktop.jar
```

**Comment by dmzettl** [comment] 2015-10-10 05:24
Completely removing the crash plan folder on the Drobo 5N and re-installing the app resolved the problem
